# Generated by Django 2.2.6 on 2020-05-11 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload_files', '0002_auto_20191022_0935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadfile',
            name='file',
            field=models.FileField(max_length=200, upload_to='uploads/'),
        ),
    ]
