# Generated by Django 2.2.6 on 2019-10-22 08:59

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_courses_is_allowed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='is_visible',
            field=models.BooleanField(default=True, verbose_name='Terlihat'),
        ),
        migrations.AlterField(
            model_name='courses',
            name='title',
            field=models.CharField(max_length=220, verbose_name='Judul'),
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=220, verbose_name='Judul')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Deskripsi')),
                ('order', models.PositiveIntegerField(verbose_name='Urut')),
                ('is_visible', models.BooleanField(default=True, verbose_name='Terlihat')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='courses.Courses')),
            ],
            options={
                'verbose_name': 'module',
                'verbose_name_plural': 'modules',
            },
        ),
    ]
