# Generated by Django 2.2.6 on 2019-10-22 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_auto_20191022_0920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskuploadsettings',
            name='max_size',
            field=models.IntegerField(help_text='Ukuran dalam MB', verbose_name='Ukuran Maks'),
        ),
    ]
