# Generated by Django 2.2.6 on 2019-10-23 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload_files', '0002_auto_20191022_0935'),
        ('courses', '0007_auto_20191022_0932'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='files',
            field=models.ManyToManyField(blank=True, null=True, to='upload_files.UploadFile'),
        ),
    ]
