# Generated by Django 2.2.6 on 2019-11-19 02:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_batch_enrollment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrollment',
            name='batch',
        ),
        migrations.AddField(
            model_name='batch',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batchs', to='courses.Courses'),
        ),
    ]
