# Generated by Django 2.2.6 on 2019-11-25 14:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('upload_files', '0002_auto_20191022_0935'),
        ('courses', '0014_auto_20191119_0235'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='module',
            options={'ordering': ['order'], 'verbose_name': 'module', 'verbose_name_plural': 'modules'},
        ),
        migrations.AlterModelOptions(
            name='section',
            options={'ordering': ['order'], 'verbose_name': 'section', 'verbose_name_plural': 'sections'},
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='allowed_access',
            field=models.BooleanField(default=False, verbose_name='Akses diberikan'),
        ),
        migrations.CreateModel(
            name='CollectTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='upload_files.UploadFile')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collect_task', to='courses.Section')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collect_task', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
