# Generated by Django 2.2.6 on 2019-11-29 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0016_activity'),
        ('courses', '0016_auto_20191129_1440'),
    ]

    operations = [
    ]
