# Generated by Django 2.2.6 on 2020-01-29 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0021_auto_20200129_0415'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='module',
            options={'ordering': ['order'], 'verbose_name': 'module', 'verbose_name_plural': 'modules'},
        ),
        migrations.AlterModelOptions(
            name='section',
            options={'ordering': ['order'], 'verbose_name': 'section', 'verbose_name_plural': 'sections'},
        ),
    ]
