# Generated by Django 2.2.6 on 2020-01-30 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0022_auto_20200129_0913'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, 'Konsep'), (2, 'Terbit')], default=2),
        ),
    ]
