# Generated by Django 2.2.6 on 2020-02-08 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0023_courses_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='collecttask',
            name='note',
            field=models.CharField(blank=True, max_length=220, null=True, verbose_name='Catatan'),
        ),
    ]
