# Generated by Django 2.2.6 on 2020-02-13 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0024_collecttask_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='link_group',
            field=models.URLField(blank=True, max_length=255),
        ),
    ]
