# Generated by Django 2.2.6 on 2020-02-21 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0025_batch_link_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, 'Daftar'), (2, 'Mulai'), (99, 'Selesai'), (100, 'Lulus')], default=2),
        ),
    ]
