# Generated by Django 2.2.6 on 2020-04-04 04:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0027_auto_20200314_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collecttask',
            name='file',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='upload_files.UploadFile'),
        ),
    ]
