# Generated by Django 2.2.6 on 2020-04-15 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0028_auto_20200404_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collecttask',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, 'Diperiksa'), (2, 'Ulangi'), (3, 'Lulus'), (4, 'Tidak Lulus')], default=1),
        ),
    ]
