# Generated by Django 2.2.6 on 2020-04-16 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0029_auto_20200415_1006'),
    ]

    operations = [
        migrations.AddField(
            model_name='collecttask',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='collecttask',
            name='update_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='module',
            name='is_visible',
            field=models.BooleanField(default=False, verbose_name='Terlihat'),
        ),
    ]
