# Generated by Django 2.2.6 on 2020-04-16 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_auto_20200416_1523'),
        ('courses', '0030_auto_20200416_1225'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='quizzes',
            field=models.ManyToManyField(to='quiz.Quiz'),
        ),
    ]
