# Generated by Django 2.2.6 on 2020-05-11 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0032_auto_20200428_1354'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='hidden_all_sections',
            field=models.BooleanField(default=False, help_text='Jika di centang maka seluruh bab pada modul ini akan terlihat', verbose_name='Bab terlihat'),
        ),
    ]
