# Generated by Django 2.2.6 on 2020-05-12 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0033_auto_20200508_0510'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='show_all_sections',
            field=models.BooleanField(default=False, help_text='Jika di centang maka seluruh bab pada modul ini akan terlihat', verbose_name='Bab terlihat'),
        ),
    ]
