# Generated by Django 2.2.6 on 2020-05-14 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0034_module_show_all_sections'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cert_title', models.CharField(blank=True, max_length=220, null=True)),
                ('prefix_cert_number', models.CharField(blank=True, max_length=50, null=True)),
                ('static_date', models.DateField(blank=True, null=True)),
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='courses.Courses')),
            ],
            options={
                'verbose_name': 'Certificate Setting',
                'verbose_name_plural': 'Certificate Settings',
            },
        ),
    ]
