# Generated by Django 2.2.6 on 2020-05-26 04:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0001_initial'),
        ('courses', '0035_certsetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vendors.Vendor', verbose_name='Vendor'),
        ),
    ]
