# Generated by Django 2.2.6 on 2020-05-26 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0035_collecttask_score'),
        ('courses', '0036_courses_vendor'),
    ]

    operations = [
    ]
