# Generated by Django 2.2.6 on 2020-06-12 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0038_auto_20200527_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collecttask',
            name='note',
            field=models.TextField(blank=True, null=True, verbose_name='Catatan'),
        ),
    ]
