# Generated by Django 2.2.6 on 2020-07-09 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0039_auto_20200612_1417'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='final_score',
            field=models.IntegerField(default=0, verbose_name='Nilai Akhir'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='note',
            field=models.TextField(blank=True, null=True, verbose_name='Catatan'),
        ),
    ]
