# Generated by Django 2.2.13 on 2020-07-21 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0040_auto_20200709_1420'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='activity',
            constraint=models.UniqueConstraint(fields=('user', 'course', 'module', 'section'), name='unique_activity'),
        ),
    ]
