# Generated by Django 2.2.13 on 2021-02-23 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0042_teach'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='can_not_copy',
            field=models.BooleanField(default=False, help_text='Aktifkan untuk membuat konten dalam kursus ini tidak dapat disalin', verbose_name='Tidak bisa salin konten'),
        ),
    ]
