# Generated by Django 2.2.13 on 2020-11-09 09:01

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0005_auto_20200922_1346'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('code', models.CharField(max_length=50, verbose_name='Kode Voucher')),
                ('discount_type', models.SmallIntegerField(blank=True, choices=[(1, 'Persentase'), (2, 'Nilai')], null=True, verbose_name='Voucher Promo Tipe')),
                ('discount_value', models.IntegerField(blank=True, null=True, verbose_name='Diskon yang Diberikan')),
                ('discount', models.IntegerField(default=0, verbose_name='Nominal Diskon')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(default='', verbose_name='Deskripsi Voucher Promo')),
                ('qty', models.PositiveIntegerField(default=0, verbose_name='Jumlah')),
                ('start_date', models.DateTimeField(auto_now_add=True, verbose_name='Tanggal Voucher Berlaku')),
                ('end_date', models.DateTimeField(auto_now_add=True, verbose_name='Tanggal Voucher Berakhir')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Dibuat pada')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Diubah pada')),
                ('product', models.ManyToManyField(to='products.Product')),
            ],
            options={
                'verbose_name': 'Voucher',
                'verbose_name_plural': 'Vouchers',
            },
        ),
        migrations.CreateModel(
            name='UserVoucher',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('status', models.SmallIntegerField(choices=[(1, 'Unused'), (2, 'Used')], default=[(1, 'Unused'), (2, 'Used')])),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Dibuat pada')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Diubah pada')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
                ('voucher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vouchers.Voucher', verbose_name='Voucher')),
            ],
            options={
                'verbose_name': 'User Voucher',
                'verbose_name_plural': 'User Vouchers',
            },
        ),
    ]
