# Generated by Django 2.2.13 on 2020-11-23 06:32

from django.db import migrations, models
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='images/vouchers/%Y/%m/%d', verbose_name='Gambar Kupon'),
        ),
        migrations.AlterField(
            model_name='uservoucher',
            name='status',
            field=models.SmallIntegerField(choices=[(1, 'Used'), (2, 'Unused')], default=2, verbose_name='Status Penggunaan Kupon'),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='code',
            field=models.CharField(max_length=50, verbose_name='Kode Kupon'),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='description',
            field=markdownx.models.MarkdownxField(default='', verbose_name='Deskripsi Kupon Promo'),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='end_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Tanggal Kupon Berakhir'),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='qty',
            field=models.PositiveIntegerField(default=0, verbose_name='Jumlah Kupon'),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='start_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Tanggal Kupon Berlaku'),
        ),
    ]
