# Generated by Django 2.2.13 on 2020-11-23 07:30

from django.db import migrations, models
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0002_auto_20201123_1332'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voucher',
            name='discount',
        ),
        migrations.AlterField(
            model_name='voucher',
            name='description',
            field=markdownx.models.MarkdownxField(default='', verbose_name='Deskripsi Kupon'),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='discount_type',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'Persentase'), (2, 'Nilai')], null=True, verbose_name='Tipe Kupon'),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='end_date',
            field=models.DateTimeField(verbose_name='Tanggal Kupon Berakhir'),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='start_date',
            field=models.DateTimeField(verbose_name='Tanggal Kupon Berlaku'),
        ),
    ]
