# Generated by Django 2.2.6 on 2020-04-28 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_auto_20200428_0946'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitting',
            name='status',
            field=models.CharField(choices=[('finish', 'Finish'), ('out_time', 'Out Time')], default='finish', max_length=50, verbose_name='Status'),
        ),
    ]
