# Generated by Django 2.2.13 on 2020-07-29 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0003_auto_20200717_1403'),
        ('quiz', '0005_sitting_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vendors.Vendor', verbose_name='Vendor'),
        ),
    ]
