# Generated by Django 2.2.13 on 2020-07-16 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='membernolsatu',
            name='role',
            field=models.PositiveIntegerField(blank=True, choices=[(1, 'Student'), (2, 'Trainer'), (3, 'Company'), (4, 'Vendor')], null=True),
        ),
    ]
