# Generated by Django 2.2.13 on 2020-07-17 07:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0002_auto_20200716_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='users',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vendors', to=settings.AUTH_USER_MODEL, verbose_name='users'),
        ),
    ]
