# Generated by Django 2.2.6 on 2019-10-22 07:52

import ckeditor.fields
import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('taggit', '0003_taggeditem_add_unique_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Judul')),
                ('short_description', ckeditor.fields.RichTextField(verbose_name='Deskripsi Singkat')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Deskripsi')),
                ('level', models.PositiveIntegerField(choices=[(1, 'Pemula'), (2, 'Menengah'), (3, 'Mahir')], verbose_name='Level')),
                ('is_visible', models.BooleanField(verbose_name='Terlihat')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to=settings.AUTH_USER_MODEL)),
                ('category', taggit.managers.TaggableManager(help_text='Kategori dipisahkan dengan koma', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Kategori')),
                ('users', models.ManyToManyField(related_name='users', to=settings.AUTH_USER_MODEL, verbose_name='users')),
            ],
            options={
                'verbose_name': '',
                'verbose_name_plural': 's',
            },
        ),
    ]
