# Generated by Django 2.2.6 on 2019-10-22 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20191022_0828'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='is_allowed',
            field=models.BooleanField(default=False, verbose_name='Diperbolehkan'),
        ),
    ]
