# Generated by Django 2.2.6 on 2019-10-22 09:10

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_auto_20191022_0859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='order',
            field=models.PositiveIntegerField(verbose_name='Urutan'),
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=220, verbose_name='Judul')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Deskripsi')),
                ('order', models.PositiveIntegerField(verbose_name='Urutan')),
                ('is_visible', models.BooleanField(default=True, verbose_name='Terlihat')),
                ('is_task', models.BooleanField(default=False, verbose_name='Tugas')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='courses.Module')),
            ],
            options={
                'verbose_name': 'module',
                'verbose_name_plural': 'modules',
            },
        ),
    ]
