# Generated by Django 2.2.6 on 2019-10-22 09:20

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('courses', '0005_auto_20191022_0910'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='section',
            options={'verbose_name': 'section', 'verbose_name_plural': 'sections'},
        ),
        migrations.CreateModel(
            name='TaskUploadSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instruction', ckeditor.fields.RichTextField(verbose_name='Instruksi')),
                ('max_size', models.IntegerField(verbose_name='Ukuran Maks')),
                ('allowed_extension', taggit.managers.TaggableManager(help_text='Extensi dipisahkan dengan koma dan tanpa titik di depan', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Ekstensi yang diizinkan ')),
                ('section', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='courses.Section')),
            ],
            options={
                'verbose_name': 'taks upload setting',
                'verbose_name_plural': 'taks upload settings',
            },
        ),
    ]
