# Generated by Django 2.2.13 on 2020-09-22 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20200918_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.SmallIntegerField(choices=[(1, 'Created'), (2, 'Success'), (3, 'Pending'), (4, 'Failed'), (5, 'Expired'), (6, 'Refund'), (7, 'Other')], default=1),
        ),
    ]
