# Generated by Django 2.2.13 on 2021-01-15 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20200922_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.SmallIntegerField(choices=[(1, 'Created'), (2, 'Success'), (3, 'Pending'), (4, 'Failed'), (5, 'Expired'), (6, 'Refund'), (7, 'Other'), (8, 'Canceled')], default=1),
        ),
    ]
